### ISSUE TITLE
Cant Allocate More RAM

### ISSUE THREAD

**Issue by SolanoB1999** [LacledesLAN/gamesvr-pzomboid#1]
It seems that the server will always start with a max of 2Gb of ram. It would be helpful to add a enviorment variable where we can set a different max limit

**Comment by Rene-Sackers** [comment]
I'm not affiliated, and only trying this image for the first time just now, but I believe you can specify the maximum RAM allocation using startup arguments.

https://pzwiki.net/wiki/Startup_parameters#JVM_arguments

Adjust your CMD to include `Xmx**m`, ex.:
```
'./start-server.sh' '-adminpassword' 'youradminpass' '-Xmx6144m' '-servername' 'myserver'
```

Side note; 6GB seems to be the sweet spot for 4 people from our testing, YMMV.

**Comment by dudleycodes** [comment]
@SolanoB1999 

@Rene-Sackers answer is the correct one. 

Project Zomboid is built on Java -- and the `Xmx` parameter is indeed how to increase the memory for the server. 

I'm going to close this issue -- but if it didn't work for you, please reply - and I'll personally dig in with you to determine what is happening.
